version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - REDIS_URL=redis://redis:6379/0
      - APP_ENV=development
  redis:
    image: redis:7
    restart: unless-stopped
